### PR TITLE
Update 11.md 

### PR DESCRIPTION
**Pull request by stoobe**
Updated financial crisis stuff

### CODE REVIEW

**Comment by cvdailyupdates** [comment]
Thank you for your comment.

Not going to merge your comment as is, specifically because "this is not a lie" only makes sense in the context of me calling it a lie, and if I merge your comment, then I'm not calling it a lie anymore, and then the comment won't make any sense. I will however replace with something like the following:


> This is heavily downplaying things. We are not going to have a _financial crisis_, as banks are well capitalized, but a recession is likely


Is this acceptable? Does it get the same message across? Or would you change it?

**Comment by stoobe** [comment]
Sounds good to me 👍 

BTW, thanks for putting this site together.  It's been really helpful.  Just figured with my background in finance I'd try to help a tiny bit.

**Comment by cvdailyupdates** [comment]
Aye. I appreciate it.

Also, I realize that in my sample alternative I still wrote "this is not a lie". Pretend I didn't say that part

**Comment by cvdailyupdates** [comment]
update pushed

**Comment by cvdailyupdates** [comment]
https://github.com/cvdailyupdates/cvdailyupdates.github.io/commit/3d7b8355e30fc5ccd1e0d67736db383fcaa7930b

**Pull request closed without merging**
